id: hl7.fhir.fr.preadmission
canonical: http://hl7.fr/fhir/fr/preadmission
name: PREADMISSIONFR
title: Guide d’Implémentation FHIR – Pré-admission Hospitalière en Ligne
publisher:
  name: Interop'Santé
  url: http://interopsante.org/
contact:
  - name: InteropSanté
    telecom:
      - system: email
        value: fhir@interopsante.org
        use: work
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2024+
releaseLabel: ci-build
jurisdiction: urn:iso:std:iso:3166#FR "FRANCE"

parameters:
  shownav: 'true'
  
dependencies:
  hl7.fhir.fr.core: 2.1.0
  # terminologyServer n'est pas une dépendance FHIR IG, à retirer

pages:
  index.md:
    title: Accueil
  processus.md:
    title: Processus fonctionnelle de la préadmission
  processus-ressource-fhir.md:
    title: Processus centré sur les ressources
  flux.md:
    title: Diagrammes des flux
  sequence.md:
    title: Diagramme de séquence du processus
  downloads.md:
    title: Téléchargement du guide
  history.md:
    title: Historique des versions

menu:
    Accueil: index.html
    Processus de préadmission:
        Processus fonctionnelle de la préadmission: processus.html
        Processus centré sur les ressources: processus-ressource-fhir.html
        Diagramme de flux: flux.html
        Diagramme de séquence: sequence.html
    Ressources de conformité: artifacts.html
    Documentations: 
        Documentation des IGs: new-tab https://interop.esante.gouv.fr/ig/documentation/
        Site d'InteropSanté: new-tab https://www.interopsante.org/
        Téléchargements: downloads.html


